#include <compte.idl>

exception CompteAlreadyExist{
	string cae;
};

exception CompteNullException{
	string cne;
};

interface IBanqueAdmin{
	boolean creationCompte(in string p_nom)raises(CompteAlreadyExist);
	boolean deleteCompte(in string p_nom);
	ICompte rechercheCompte(in string p_nom)raises(CompteNullException); 
};